config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"

  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   # 会員側のルーティング設定

   scope module: :public do
    get '/customers/mypage', to:'customers#show'
    get '/customers/infomation/edit', to:'customers#edit'
    patch '/customers/infomation', to:'customers#update'
    get '/customers/withdrawal', to:'customers#withdrawal'
    patch '/customers/withdraw', to:'customers#withdraw'
    root to: 'homes#top'
    resources :items
    delete '/cart_items/destroy_all', to:'cart_items#destroy_all'
    resources :cart_items
    get '/orders/complete', to:'orders#complete'
    post '/orders/confirm', to:'orders#confirm'
    resources :orders
    resources :addresses
    # 管理者側のルーティング設定
  end
   namespace :admin do
    root 'homes#top'
    resources :homes
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  get '/about', to: 'public/homes#about', as: 'about'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample.png')
      image.attach(io: File.open(file_path), filename: 'sample.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum status: {awaiting_payment:0, confirmation_of_payment: 1, in_production: 2, preparing_to_ship: 3, shipped: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {unable_to_produce:0, waiting_for_production: 1, under_production: 2, production_complete: 3}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if  @customer.update(customer_params)
      flash[:notice] = "You have updated customer successfully."
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

   private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :email, :telephone_number, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  # 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genres = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genres.save
    # 4. トップ画面へリダイレクト
    redirect_to admin_genres_path
  end

  def edit

  end

private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
   @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    item = Item.new(item_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    item.save!
    # 4. トップ画面へリダイレクト
    redirect_to admin_item_path(item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admin_order_path(order.id)
  end

  private
  # ストロングパラメータ
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status, :created_at)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
会員情報編集

  <table class="table table-borderless" style="width:45%;margin-left:5%;margin-top:40px">
   <tbody>
    <%= form_with model: @customer, url: admin_customer_path(@customer), method: :PATCH do |f| %>
    <tr>
     <td>会員ID</td>
     <td>1</td>
    </tr>
    <tr>
     <td>氏名</td>
     <td><%= f.text_field :last_name %></td>
     <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
     <td>フリガナ</td>
     <td><%= f.text_field :last_name_kana %></td>
     <td><%= f.text_field :first_name_kana %></td>
    </tr>
    <tr>
     <td>郵便番号</td>
     <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
     <td>住所</td>
     <td><%= f.text_field :address %></td>
    </tr>
    <tr>
     <td>電話番号</td>
     <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
     <td>メールアドレス</td>
     <td><%= f.text_field :email %></td>
    </tr>
    <tr>
     <td>会員ステータス</td>
     <td><%= f.radio_button :is_deleted, false %>有効</td>
     <td><%= f.radio_button :is_deleted, true %>退会</td>
    </tr>
    <tr>
     <td></td>
     <td><%= f.submit "変更を保存",class: "btn btn-success" %></td>
    </tr>
    <% end %>
   </tbody>
  </table>

app/views/admin/customers/index.html.erb
会員一覧
<div>
  <div class="d-flex justify-content-center">
  <!-- form_with部分 -->
  <%= form_with model: Genre.new, url: admin_genres_path,method: :post do |f| %>

<table class="table table-borderless">
  <tbody>
    <tr class="table-secondary">
      <td>会員ID</td>
      <td>氏名</td>
      <td>メールアドレス</td>
      <td>ステータス</td>
    </tr>

    <% @customers.each do |customer| %>

    <tr>
      <td><%= customer.id %></td>
      <td>
        <%= link_to admin_customer_path(customer.id) do %>
        <%= customer.last_name %><%=customer.first_name %>
        <% end %>
      </td>
      <td><%= customer.email %></td>
        <td>
        <% if customer.is_deleted? %>
        退会
        <% else %>
        有効
        <% end %>
      </td>
    </tr>
    <% end %>

    <tr>
      <td></td>
      <td>1 2 3 Next > Last ≫</td>
      <td></td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/admin/customers/show.html.erb
会員詳細

<table class="table table-borderless" style="width:40%;margin-left:5%;margin-top:40px">
  <tbody>
    <tr>
      <td>会員ID</td>
      <td>1</td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><p><%= @customer.last_name %><%= @customer.first_name %></p></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><p><%= @customer.last_name_kana %><%= @customer.first_name_kana %></p></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><p><%= @customer.postal_code %></p></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><p><%= @customer.address %></p></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><p><%= @customer.telephone_number %></p></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><p><%= @customer.email %></p></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td class="text-success"><%= @customer.is_deleted ? "退会" : "有効" %></td>
    </tr>
    <tr>
      <td></td>
      <td class= "btn btn-success"><%= link_to '編集する', edit_admin_customer_path(@customer.id), class:"text-light" %></td>
      <td></td>
      <td class= "btn btn-primary"><%= link_to '注文履歴一覧を見る', admin_root_path, class:"text-light" %></td>
    </tr>
  </tbody>
</table>