config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"

  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   # 会員側のルーティング設定

   scope module: :public do
    get '/customers/mypage', to:'customers#show'
    get '/customers/infomation/edit', to:'customers#edit'
    patch '/customers/infomation', to:'customers#update'
    get '/customers/withdrawal', to:'customers#withdrawal'
    patch '/customers/withdraw', to:'customers#withdraw'
    root to: 'homes#top'
    resources :items
    delete '/cart_items/destroy_all', to:'cart_items#destroy_all'
    resources :cart_items
    get '/orders/complete', to:'orders#complete'
    post '/orders/confirm', to:'orders#confirm'
    resources :orders
    resources :addresses
    # 管理者側のルーティング設定
  end
   namespace :admin do
    root 'homes#top'
    resources :homes
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  get '/about', to: 'public/homes#about', as: 'about'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample.png')
      image.attach(io: File.open(file_path), filename: 'sample.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum status: {awaiting_payment:0, confirmation_of_payment: 1, in_production: 2, preparing_to_ship: 3, shipped: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {unable_to_produce:0, waiting_for_production: 1, under_production: 2, production_complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  # 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genres = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genres.save
    # 4. トップ画面へリダイレクト
    redirect_to admin_genres_path
  end

  def edit

  end

private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
   @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    item = Item.new(item_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    item.save!
    # 4. トップ画面へリダイレクト
    redirect_to admin_item_path(item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to admin_order_path(order.id)
  end

  private
  # ストロングパラメータ
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status, :created_at)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
ジャンル編集

<%= form_with model: Genre.new, url: admin_genres_path,method: :post do |f| %>

  ジャンル名
  <%= f.text_field :name %>
  <%= f.submit '変更を保存', class: "btn btn-success" %>
<% end %>

app/views/admin/genres/index.html.erb
ジャンル一覧・追加

<table class="table table-hover table-inverse" style="width:35%;margin-left:5%">
  <tbody>
    <%= form_with model: Genre.new, url: admin_genres_path,method: :post do |f| %>
    <tr>
      <td>ジャンル名</td>
      <td><%= f.text_field :name %></td>
      <td><%= f.submit '新規登録', class: "btn btn-success" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<table class="table table-hover table-inverse" style="width:30%;margin-left:5%;margin-top:40px">
  <thead class="bg-secondary">
    <tr>
      <th>ジャンル</th>
      <th></th>
     </tr>
  </thead>
  <tbody>
  <% @genres.each do |genre| %>
  <tr>
   <td><%= genre.name %></td>
   <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
  <tr>
  <% end %>
 </tbody>
</table>

app/views/admin/items/edit.html.erb
<div style="width:80%;margin-left:20%;margin-top:30px">
  <h5>商品編集</5>
</div>

<table class="table table-borderless" style="width:50%;margin-left:30%;margin-top:60px">
  <tbody>
  <%= form_with model: @item, url: admin_item_path,method: :patch do |f| %>
    <tr>
      <td>商品画面</td>
      <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    <tr>
      <td>商品名</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= f.text_field :introduction %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
    </tr>
    <tr>
      <td>税抜価格</td>
      <td><%= f.text_field :price %>円</td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td><%= f.radio_button :is_active, true %>販売中</td>
      <td><%= f.radio_button :is_active, false %>販売停止中</td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
      <td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/items/index.html.erb
<%= form_with model: Genre.new, url: admin_genres_path,method: :post do |f| %>
<table class="table table-borderless" class="table table-borderless" style="width:70%;margin-left:15%;margin-top:20px">
  <tbody>
     <tr>
      <td><h5>商品一覧</h5></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= link_to "新規登録", new_admin_item_path %></td>
     </tr>
    <tr class="table-secondary">
      <td>商品ID</td>
      <td>商品名</td>
      <td>税抜価格</td>
      <td>ジャンル</td>
      <td>ステータス</td>
    </tr>
    <% @items.each do |item| %>
    <tr>
      <td>
        <%= item.id %>
      </td>
      <td>
        <%= link_to item.name, admin_item_path(item.id)%>
      </td>
      <td><%= item.price %></td>
      <td>
        <%= item.genre.name %>
      </td>
      <td>
        <% if item.is_active? %>
        販売中
        <% else %>
        販売停止中
        <% end %>
      </td>
    </tr>
<% end %>
    <tr>
      <td></td>
      <td>1 2 3 Next > Last ≫</td>
      <td></td>
    </tr>
  </tbody>
</table>
</div>
<% end %>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<div style="width:80%;margin-left:20%;margin-top:30px">
  <h5>商品新規登録</5>
</div>

<table class="table table-borderless" style="width:50%;margin-left:30%;margin-top:40px">
  <tbody>
    <%= form_with model: Item.new, url: admin_items_path,method: :post do |f| %>
    <tr>
      <td>商品画面</td>
      <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
    <tr>
      <td>商品名</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= f.text_field :introduction %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
    </tr>
    <tr>
      <td>税抜価格</td>
      <td><%= f.text_field :price %>円</td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td><%= f.radio_button :is_active, true %>販売中</td>
      <td><%= f.radio_button :is_active, false %>販売停止中</td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit '新規登録', class: "btn btn-success" %></td>
      <td></td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/admin/items/show.html.erb
<div style="width:80%;margin-left:20%;margin-top:30px">
  <h5>商品詳細</5>
</div>

<div class="table table-borderless" style="width:80%;margin-left:5%;margin-top:60px">
<div class="container">
  <div class="row">
    <div class="col-1">
    </div>
    <div class="col-3">
      <%= image_tag @item.image, size: "250x150" %>
    </div>
    <div class="col-8">
      <table class="table table-borderless" >
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>税込価格(税抜価格)</td>
            <td><%= @item.price %>円</td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <% if @item.is_active == true %>
            <td class="text-success">販売中</td>
            <% else %>
            <td class="text-success">販売停止中</td>
            <% end %>
          </tr>
          <tr>
            <td></td>
            <td class= "btn btn-success"><%= link_to '編集する', edit_admin_item_path(@item.id), class:"text-light" %></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
注文履歴詳細 show

<table class="table table-borderless" style="width:50%;margin-left:9%;margin-top:60px">
  <tbody>
    <tr>
      <td>購入者</td>
      <td><%= link_to @order.name, admin_customer_path %></td>
    </tr>
    <tr>
      <td>注文日</td>
      <td><%= @order.created_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <td>配送先</td>
      <td><%= @order.postal_code %>
          <%= @order.address %>
          <%= @order.name %>
      </td>
    </tr>
    <tr>
      <td>支払方法</td>
      <td><%= Order.payment_methods_i18n[@order.payment_method] %></td>
    </tr>
    <tr>
      <td>注文ステータス</td>
      <%=form_with model: @order, url: admin_order_path, method: :patch do |f| %>
      <td><%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %></td>
      <td><%= f.submit '更新',class: "btn btn-success"  %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<div class="row mx-auto col-md-10">
<table class="table table-borderless col-md-7">
  <tbody>
    <tr class="table-secondary">
      <td>商品名</td>
      <td>単価（税込）</td>
      <td>数量</td>
      <td>小計</td>
      <td>製作ステータス</td>
    </tr>
     <% @order_details.each do |order_detail| %>
      <td>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= order_detail.price*order_detail.amount %></td>
          <%=form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
          <%= f.hidden_field :order_id, :value => @order.id %>
          <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %></td>
          <td><%= f.submit '更新',class: "btn btn-success"  %></td>
          <% end %>
        </tr>
       </td>
     <% end %>
  </tbody>
</table>

<div class= "col-md-5">
  <div class= "row"></div>
  <tr>
   <div class="aaa">
    <td>商品合計</td>
    <% @total = @order.total_payment-@order.shipping_cost %>
    <%= @total %>円
   </div>
   <div>
    <td>送料</td>
    <%= @order.shipping_cost %>円
   </div>
   <div>
    <td>請求金額合計</td>
    <%= @order.total_payment %>円
   </div>
  </tr>
</div>
</div>