config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"

  }


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   # 会員側のルーティング設定

   scope module: :public do
    get '/customers/mypage', to:'customers#show'
    get '/customers/infomation/edit', to:'customers#edit'
    patch '/customers/infomation', to:'customers#update'
    get '/customers/withdrawal', to:'customers#withdrawal'
    patch '/customers/withdraw', to:'customers#withdraw'
    root to: 'homes#top'
    resources :items
    delete '/cart_items/destroy_all', to:'cart_items#destroy_all'
    resources :cart_items
    get '/orders/complete', to:'orders#complete'
    post '/orders/confirm', to:'orders#confirm'
    resources :orders
    resources :addresses
    # 管理者側のルーティング設定
  end
   namespace :admin do
    root 'homes#top'
    resources :homes
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details, only: [:update]
  end
  get '/about', to: 'public/homes#about', as: 'about'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details
  has_many :cart_items, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample.png')
      image.attach(io: File.open(file_path), filename: 'sample.png', content_type: 'image/png')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum status: {awaiting_payment:0, confirmation_of_payment: 1, in_production: 2, preparing_to_ship: 3, shipped: 4}
  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {unable_to_produce:0, waiting_for_production: 1, under_production: 2, production_complete: 3}
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  # 以下を追加
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    genres = Genre.new(genre_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    genres.save
    # 4. トップ画面へリダイレクト
    redirect_to admin_genres_path
  end

  def edit

  end

private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
   @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new

  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    item = Item.new(item_params)
    # 3. データをデータベースに保存するためのsaveメソッド実行
    item.save!
    # 4. トップ画面へリダイレクト
    redirect_to admin_item_path(item.id)
  end

  private
  # ストロングパラメータ
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>LOGO</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
        <!--adminでログインしているときのヘッダー-->
          <li>
            <%= link_to admin_items_path do %>
              <i class="fas fa-home"></i>商品一覧
            <% end %>

            <%= link_to admin_customers_path do %>
              <i class="fas fa-users"></i>会員一覧
            <% end %>

            <%= link_to admin_root_path do %>
              <i class="fas fa-book-open"></i>注文履歴一覧
            <% end %>

            <%= link_to admin_genres_path do %>
              <i class="fas fa-home"></i>ジャンル一覧
            <% end %>

            <%= link_to destroy_admin_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>

      <!--adminでログアウトしているときのヘッダー-->


        <!--customerでログインしているときのヘッダー-->
        <% elsif customer_signed_in? %>
          <li>
            <%= link_to customers_mypage_path do %>
              <i class="fas fa-user"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to items_path do %>
              <i class="fas fa-users-slash"></i>商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path do %>
              <i class="fa-solid fa-cart-shopping"></i>カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete do %>
              <i class="fas fa-sign-out"></i>ログアウト
            <% end %>
          </li>
        <% else %>

        <!--customerでログアウトしているときのヘッダー-->
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "商品一覧", items_path %>
        </li>
        <li>
          <%= link_to "新規登録", new_customer_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_customer_session_path %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <%= yield %>
  </body>
</html>